name: flutter_story
description: A Flutter story application with authentication and story management.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  device_info_plus: ^11.4.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^2.4.1
  geocoding: ^4.0.0
  geolocator: ^14.0.1
  go_router: ^15.1.2
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.12.2
  http: ^1.1.2
  image_picker: ^1.0.4
  intl: ^0.20.2
  json_annotation: ^4.9.0
  path: ^1.8.3
  permission_handler: ^12.0.0+1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.3
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  #   - assets/icons/
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/logo/logo.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/logo/logo.png"
  windows:
    generate: true
    image_path: "assets/logo/logo.png"
  macos:
    generate: true
    image_path: "assets/logo/logo.png"
  linux:
    generate: true
    image_path: "assets/logo/logo.png"